# Generated by Django 4.2.21 on 2025-06-01 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسندگان'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'کانال', 'verbose_name_plural': 'کانال\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='channelmember',
            options={'verbose_name': 'عضویت کانال', 'verbose_name_plural': 'عضویت کانال\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'verbose_name': 'پلتفرم', 'verbose_name_plural': 'پلتفرم\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AddField(
            model_name='author',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporter.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام نویسنده'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='audience',
            field=models.CharField(max_length=100, verbose_name='مخاطب'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='آیدی کانال'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateField(verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام کانال'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='channel_pictures/', verbose_name='عکس کانال'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.platform', verbose_name='پلتفرم'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='sub_topic',
            field=models.CharField(max_length=100, verbose_name='زیر موضوع'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reporter.channel', verbose_name='کانال'),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='collected_at',
            field=models.DateField(verbose_name='تاریخ جمع\u200cآوری'),
        ),
        migrations.AlterField(
            model_name='channelmember',
            name='member_count',
            field=models.PositiveIntegerField(verbose_name='تعداد عضو'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(upload_to='platform_logos/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام پلتفرم'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.author', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='reporter.channel', verbose_name='کانال'),
        ),
        migrations.AlterField(
            model_name='post',
            name='collected_at',
            field=models.DateField(verbose_name='تاریخ جمع\u200cآوری'),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.TextField(verbose_name='هشتگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(verbose_name='متن پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام استان'),
        ),
    ]
