# Generated by Django 4.2.21 on 2025-06-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_author_address_author_bio_author_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='other', max_length=10, verbose_name='جنسیت'),
        ),
    ]
