# Generated by Django 4.2.21 on 2025-05-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_id', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='posts/')),
                ('scheduled_time', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('channels', models.ManyToManyField(to='sender.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.province'),
        ),
    ]
