# Generated by Django 4.2.21 on 2025-05-21 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0003_remove_post_error_message_post_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='allowed_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
