# Generated by Django 4.2.21 on 2025-05-22 07:04

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_channel_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'کانال', 'verbose_name_plural': 'کانال ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'مرکز', 'verbose_name_plural': 'مراکز'},
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
