# Generated by Django 4.2.21 on 2025-05-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0006_alter_post_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.CharField(choices=[('bale', 'bale'), ('eitaa', 'eitaa')], max_length=20),
        ),
    ]
