# Generated by Django 4.2.21 on 2025-05-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0008_category_channel_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
