# Generated by Django 4.2.21 on 2025-05-25 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0009_alter_category_options_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sender.category', verbose_name='ارسال به تمام کانال\u200cهای دسته\u200cبندی'),
        ),
    ]
