# Generated by Django 4.2.21 on 2025-05-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0010_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa')], max_length=20, unique=True, verbose_name='پلتفرم')),
                ('token', models.CharField(max_length=100, verbose_name='توکن API')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'توکن پلتفرم',
                'verbose_name_plural': 'توکن\u200cهای پلتفرم',
            },
        ),
    ]
