# Generated by Django 4.2.21 on 2025-05-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0011_platformtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa')], max_length=20),
        ),
    ]
