# Generated by Django 4.2.21 on 2025-05-28 05:15

from django.db import migrations, models
import sender.models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0012_alter_channel_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='posts/media/', validators=[sender.models.validate_media], verbose_name='تصویر یا ویدئو'),
        ),
    ]
