# Generated by Django 4.2.21 on 2025-05-31 10:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0013_remove_post_image_post_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('Telegram', 'Telegram'), ('Instagram', 'Instagram')], max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('subtopic', models.CharField(max_length=100)),
                ('audience', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sender.province')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField()),
                ('hashtag', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.dashboardchannel')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.PositiveIntegerField()),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.dashboardchannel')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
    ]
