# Generated by Django 4.2.21 on 2025-05-31 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0015_platform_alter_channelstats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sender.platform'),
        ),
    ]
