# Generated by Django 4.2.21 on 2025-05-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0016_alter_channel_platform'),
    ]

    operations = [
    ]
