# Generated by Django 4.2.21 on 2025-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0017_auto_20250531_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
