# Generated by Django 4.2.21 on 2025-05-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0018_alter_channel_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sender.platform'),
        ),
    ]
