# Generated by Django 4.2.21 on 2025-06-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0019_alter_channel_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardchannel',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='dashboardchannel',
            name='province',
        ),
        migrations.RemoveField(
            model_name='platformpost',
            name='channel',
        ),
        migrations.AlterField(
            model_name='channel',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformtoken',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('bale', 'Bale'), ('eitaa', 'Eitaa')], default='', max_length=20, unique=True, verbose_name='پلتفرم'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChannelStats',
        ),
        migrations.DeleteModel(
            name='DashboardChannel',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='PlatformPost',
        ),
    ]
