# Generated by Django 4.2.21 on 2025-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0020_remove_dashboardchannel_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.TextField(blank=True, help_text='هر هشتگ در یک خط و با فاصله جدا شوند.', null=True, verbose_name='هشتگ\u200cها'),
        ),
        migrations.AddField(
            model_name='post',
            name='titr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان'),
        ),
    ]
